bwsess

diff --git a/dot_zshrc.tmpl b/dot_zshrc.tmpl
--- a/dot_zshrc.tmpl
+++ b/dot_zshrc.tmpl
@@ -121,6 +121,19 @@ bw_sess_ttl=3600 # 1 hour
 if [[ ! -e "$bw_sess_file" ]]; then
   # Create the file and any necessary directories
   mkdir -p "$(dirname "$bw_sess_file")" && touch "$bw_sess_file"
+  # Retry until the command exits with 0
+  while true; do
+    # Set BW_SESSION with the result of "bw unlock --raw"
+    BW_SESSION="$(bw unlock --raw)"
+    # Check if the command exited with 0
+    if [[ $? -eq 0 ]]; then
+      # Write BW_SESSION to the file
+      echo "$BW_SESSION" > "$bw_sess_file"
+      # Export BW_SESSION
+      export BW_SESSION="$BW_SESSION"
+      break
+    fi
+  done
 fi
 
 # Get the last modification time of the file in seconds since epoch
@@ -138,7 +151,7 @@ if [[ $time_diff -le $bw_sess_ttl ]]; then
   export BW_SESSION="$(cat "$bw_sess_file")"
 else
   # Clear the Bitwarden session file
-  >$bw_sess_file
+  echo >$bw_sess_file
   # Retry until the command exits with 0
   while true; do
     # Set BW_SESSION with the result of "bw unlock --raw"
